### ISSUE TITLE
RE: BBAI and Not Using Make/Make Install

### ISSUE THREAD

**Issue by silver2row** [shabaz123/iobb#1]
Hello,

Do you think it is possible to use this library with the BBAI if I do not make and make install the library once I clone it?

Seth

P.S. I can and will change some source to make things work but I am not sure I understand exactly how just yet. If you have any ideas, I am all ears. If you are willing to work alongside someone else, me, please let me know. I know we are strangers. Sorry for the oddball ideas. For instance, I was told that GPIO3_12 or P9_15 is numbered like this: 2 * 32 + 12 = 76 instead of 3 * 32 + 12 = xxx. For whatever reason, I just believed the person. If you know better, please let me know.

**Comment by shabaz123** [comment]
Hi,
It won't work with BB-AI. To modify it is a large task, a rough estimate is 1 full week of effort (maybe shorter for someone experienced with the BB-AI's chip which I'm not) to get some of it working, and another week to refine it. I did start looking into it a few months ago, but I can only dedicate a short amount of time at any one go, so it has stalled until I find time. Anyone who wishes to work on it would need to go through the multi-thousand page technical reference manual for the chip. It's not insurmountable, just a lot of effort. The GPIO pin names are just one part of the effort, there are other differences (such as module and clock enablement register names), and some time is needed for reading and learning how this works.

**Comment by silver2row** [comment]
Okay,

Hello...no issue here. I guess it may be out of my realm. I am more of a pick and place person for now. Anyway, thank you for this library. I will test it on my BBBW and BBB.

Seth
